export const AUTH_USER_LOGGED_IN = 'AUTH_USER_LOGGED_IN';
export const AUTH_USER_LOGGED_OUT = 'AUTH_USER_LOGGED_OUT';

export const USER_PROFILE_SET = 'USER_PROFILE_SET';
export const USER_BALANCE_SET = 'USER_BALANCE_SET';

export const USER_TRANSACTIONS = 'USER_TRANSACTIONS';
export const USER_TICKETS = 'USER_TICKETS';
export const USER_PRODIUCTS = 'USER_PRODIUCTS';

export const GAME_PLAY_STATUS = 'GAME_PLAY_STATUS';

export const STORE_CREDENTIALS = 'STORE_CREDENTIALS';
export const CLEAR_CREDENTIALS = 'CLEAR_CREDENTIALS';