export const AUTH_USER_LOGGED_IN = 'AUTH_USER_LOGGED_IN';
export const AUTH_USER_LOGGED_OUT = 'AUTH_USER_LOGGED_OUT';

export const USER_BALANCE_SET = 'USER_BALANCE_SET';

export const GAME_PLAY_STATUS = 'GAME_PLAY_STATUS';